### PR TITLE
EditorLinkDialog should validate URLs, and autocomplete like the Link…

### PR DESCRIPTION
**Pull request by DevinCarlson**
… widget.

### CODE REVIEW

**Comment by saltednut** [comment]
This looks cool, but I would say to be fully functional for a regular user, you would want to make two small changes.
1.  When I inserted a node titled "Test" with the url `content/test` it made its way into the editor as "content/test"  -- i would think the insertion should make the link text the node:title and the link should be node:uri.  So `<a href="[node:uri]">[node:title]</a>`
2. It would be great to be able to edit the Link text inside the dialogue, so that its 100% intuitive.  I would think this "Link text" would be auto-filled with [node:title] and one could change it.

Aside from that, this is totally functional (I can edit the link text inside the wysiwyg) so I'd say just update the patch and we're good to go.

**Comment by saltednut** [comment]
So this is looking better.  One thing that I think we've overlooked:  How does one create a link manually now?  I should be able to make a hyperlink that is not internal.  The new system only provides links for internal content.

**Comment by DevinCarlson** [comment]
You can create a link to any valid URL by default or whenever an entity type is not selected.

This is indicated by the field title (URL vs. Entity depending on whether a selection has been made) and via the Entity Type help text: "Optionally create links to existing entities by selecting an entity type".

**Comment by saltednut** [comment]
Gotcha.  I figured that out after a few more tries with it.  IMO that doesn't seem intuitive, so I am wondering if we can do something with the form to make it more obvious that one does not have to choose an entity type first.  Given the field is optional, but also the first field on the form, its very confusing.

**Comment by saltednut** [comment]
Lets bring this in and followup with a solution that makes the UI more intuitive for media laymen such as myself :)

**Pull request merged**
