### PR TITLE
Updated all media-related modules to the latest releases.

### PR DESCRIPTION
**Pull request by DevinCarlson**

### CODE REVIEW

**Comment by saltednut** [comment]
There are two issues preventing a merge:
1.  Entity Embed - when adding an image via ckeditor, the ctools modal does not close once an item is selected and if you use the Library tab it will say "You haven't selected anything" in an alert. One can close the modal manually and see that the thing they selected did make it into the dialog for embedding.
2.  When attempting to use the "Content" FPP, adding the pane to a Panelized page, the "Add items" button does not open up a dialog. It just shows a throbber for a second then stops. No errors logged in the console.

@mortenson please test this PR and confirm if you are also seeing these issues.

**Comment by mortenson** [comment]
I can't replicate those issues, although I'm building this by running ./update.sh in lightning-build (on Devin's branch). Not sure if that's the right way to go about things.

**Comment by saltednut** [comment]
I tested again and saw the same errors.  Here are some gifs.

It seems like two modals are actually popping up when one uses CKeditor and Entity Embed
entity_embed

Cannot use the dialog selection to add nodes to the "Content" FPP
dialog

**Comment by mortenson** [comment]
I can confirm both issues.

**Comment by saltednut** [comment]
@DevinCarlson any updates for this?

**Comment by saltednut** [comment]
The first issue, Entity Embed for CKEditor, is now fixed.

The second issue with the new dialog version breaking the content FPP entityreference_view_widget persists.

**Pull request merged**
